M48
; DRILL file KiCad 10.0.6 date 2026-09-25T04:31:35
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-25T04:31:35-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X7.46Y-35.4
X12.54Y-34.384
X12.54Y-36.416
T2
X16.514Y-4.35
X16.514Y-12.1
M30
