M48
; DRILL file KiCad 10.0.6 date 2026-09-23T10:07:27
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-23T10:07:27-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X15.504Y-22.06
X16.52Y-27.14
X17.536Y-22.06
T2
X13.23Y-17.7
X17.95Y-17.7
M30
